import type { Lang } from '../data/cv';

export const ui = {
  en: {
    metaTitle: 'Naun Flores, Senior Odoo Developer',
    metaDescription:
      'Résumé of Naun Flores: systems engineer, Senior Odoo Developer (versions 11 to 19) and functional consultant for accounting and payroll.',
    skip: 'Skip to content',
    downloadPdf: 'Download résumé (PDF)',
    downloadDocx: 'DOCX',
    switchLang: 'Español',
    themeToggle: 'Toggle dark mode',
    railCaption: 'Odoo releases I have worked with',
    summary: 'Profile',
    experience: 'Experience',
    expertise: 'Functional expertise',
    technical: 'Technical skills',
    education: 'Education',
    certifications: 'Certifications',
    languages: 'Languages',
    contact: 'Contact',
    contactText: 'The fastest way to reach me is LinkedIn.',
    updated: 'Last updated',
  },
  es: {
    metaTitle: 'Naun Flores, Developer Senior Odoo',
    metaDescription:
      'CV de Naun Flores: ingeniero de sistemas, Developer Senior Odoo (versiones 11 a 19) y consultor funcional de contabilidad y nómina.',
    skip: 'Saltar al contenido',
    downloadPdf: 'Descargar CV (PDF)',
    downloadDocx: 'DOCX',
    switchLang: 'English',
    themeToggle: 'Cambiar modo oscuro',
    railCaption: 'Versiones de Odoo con las que he trabajado',
    summary: 'Perfil',
    experience: 'Experiencia',
    expertise: 'Áreas funcionales',
    technical: 'Habilidades técnicas',
    education: 'Educación',
    certifications: 'Certificaciones',
    languages: 'Idiomas',
    contact: 'Contacto',
    contactText: 'La forma más rápida de contactarme es LinkedIn.',
    updated: 'Actualizado',
  },
} satisfies Record<Lang, Record<string, string>>;

/** Résumé files generated by `npm run cv` into public/cv/. */
export const cvFiles: Record<Lang, { pdf: string; docx: string }> = {
  en: { pdf: '/cv/Naun_Flores_Resume_EN.pdf', docx: '/cv/Naun_Flores_Resume_EN.docx' },
  es: { pdf: '/cv/Naun_Flores_CV_ES.pdf', docx: '/cv/Naun_Flores_CV_ES.docx' },
};
